name: First Workflow
on: [push]
jobs:
    check-ram:
        runs-on: ubuntu-latest
        steps:
            - name: Check RAM
              run: free -m
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello world"
            - name: Multiline comments
              run: |
                node -v
                npm -v
    parallel-job-macos:
      runs-on: macos-latest
      steps: 
        - name: View SW Version
          run: sw_vers
    dependent-job:
        runs-on: windows-latest
        needs: run-shell-commands
        steps: 
            - name: echo a string
              run: Write-Output 'Windows String'
            - name: Error Step
              run: doesnotexistss



