name: Workflow commands
on: [push]

jobs:
    testign-of-commands: 
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missing semicolon"
            - name: Setting error messgae with parameters
              run: echo "::error title:Error Title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing SemiColon"